apiVersion: apps/v1
kind: Deployment
metadata:
  name: fasterrcnn-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fasterrcnn-api
  template:
    metadata:
      labels:
        app: fasterrcnn-api
    spec:
      containers:
      - name: fasterrcnn-api
        image: fasterrcnn-api:latest
        imagePullPolicy: Never   # important: don't pull from registry
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fasterrcnn-api-service
spec:
  type: NodePort
  selector:
    app: ffasterrcnn-api
  ports:
  - port: 8080
    targetPort: 8080